external NFS server and persistent volume backup/restore

diff --git a/templates/restore_dtr_metadata.sh.j2 b/templates/restore_dtr_metadata.sh.j2
--- a/templates/restore_dtr_metadata.sh.j2
+++ b/templates/restore_dtr_metadata.sh.j2
@@ -27,7 +27,17 @@ else
   ucp_insecure_switch="--ucp-insecure-tls"
   env_switch=""
 fi
-nfs_server="{% if dtr_external_nfs is defined%}{{ dtr_external_nfs}}{% else %}{{ hostvars[groups['nfs'][0]].ip_addr | ipaddr('address') }}{% endif %}"
+nfs_server="{{ ivar_nfs_server }}"
+
+nfs_volume="{{ dtr_volume_backend_name }}"
+volume=$(docker volume ls | awk "/$nfs_volume/ {print \$2}")
+if [ "$volume" == "$nfs_volume" ]
+then
+  echo Volume $nfs_volume was found
+else
+ echo "$0 the expected volume cannot be found, aborting"
+ exit 1
+fi
 
 ssh -oStrictHostKeyChecking=no {{ backup_server }} "cat {{ backup_dtr_meta }}" | zcat | \
   docker run -i --rm --env UCP_USERNAME --env UCP_PASSWORD $env_switch docker/dtr:{{ dtr_version }} restore \
@@ -36,5 +46,5 @@ ssh -oStrictHostKeyChecking=no {{ backup_server }} "cat {{ backup_dtr_meta }}" |
     --ucp-node {{ groups.dtr_main[0] }}.{{ domain_name }} \
     --replica-id ${replica_id}  \
     --dtr-external-url https://{{ groups.dtr[0] }}.{{ domain_name }} \
-    --nfs-storage-url nfs://${nfs_server}{{ images_folder }}\
+    --dtr-storage-volume $nfs_volume  \
     {{ http_proxy_switch }} {{ https_proxy_switch }} {{ no_proxy_switch }} 
